name: build

on:
  pull_request:
    branches: [ main, develop, 'feature-*', 'fix-*', 'hotfix-*', 'release-*' ]

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [lint, test]

    steps:
      - name: Build Android codes
        run:
          echo "Building Android codes"

  ios:
    runs-on: macos-latest
    timeout-minutes: 60
    needs: [lint, test]

    steps:
      - name: Build iOS codes
        run:
          echo "Building iOS codes"

      - name: Get release version
        id: version_check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show release version
        run:
          echo ${{ steps.version_check.outputs.version }}
