name: Build APKs

on:
  push:
    tags:
      - 'android-*'

jobs:
  build-apks:
    runs-on: ubuntu-latest
    steps:
      - name: Build APKs
        run:
          echo "Building APKs"
      #- uses: actions/checkout@v2

      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '16.15.0'

      #- name: Check if version has been updated
      #  id: version_check
      #  uses: EndBug/version-check@v2
      #  with:
      #    diff-search: true
      #    token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Build Ionic
      #  env:
      #    NUMBERS_STORAGE_BASE_URL: ${{ secrets[matrix.storage_base_url] }}
      #    NUMBERS_STORAGE_TRUSTED_CLIENT_KEY: ${{ secrets[matrix.storage_trusted_client_key] }}
      #    NUMBERS_BUBBLE_DB_URL: ${{ secrets[matrix.bubble_db_url] }}
      #    BUBBLE_API_URL: ${{ secrets.BUBBLE_API_URL }}
      #  run: |
      #    npm install -g @ionic/cli
      #    npm install
      #    npm run build

      #- name: Build APKs
      #  run: |
      #    npx cap sync android
      #    cd android/
      #    ./gradlew assembleDebug

      #- name: Upload matrix build outputs to Google Drive
      #  uses: numbersprotocol/action-google-drive@master
      #  with:
      #    skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
      #    google-client-id: ${{ secrets.SKICKA_GOOGLE_CLIENT_ID }}
      #    google-client-secret: ${{ secrets.SKICKA_GOOGLE_CLIENT_SECRET }}
      #    upload-from: ./android/app/build/outputs/apk/debug/
      #    upload-to: /capture-lite/apk/${{github.ref_name}}/${{ matrix.folder_name }}/
