name: pre-release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '16.15.0'

      - name: Debug
        uses: crazy-max/ghaction-dump-context@v1

      - name: Check if version has been updated
        id: version_check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Echo
        run:
          echo ${{ steps.version_check.outputs.version }}
          echo ${{ steps.tag.outputs.result }}
          echo ${{ steps.get_version.outputs.version }}

      #- name: Create GitHub prerelease
      #  id: create_release
      #  # context property
      #  if: steps.version_check.outputs.changed == 'true'
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{ steps.version_check.outputs.version }}
      #    release_name: ${{ steps.version_check.outputs.version }}
      #    body: Thanks for following along! For more information check out the [CHANGELOG](https://github.com/bafu/hackga/blob/master/CHANGELOG.md).
      #    prerelease: true

      - name: Create GitHub prerelease
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: Thanks for following along! For more information check out the [CHANGELOG](https://coming.soon).
          files: |
            bumper.txt
            LICENSE
          prerelease: true

  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload my bumper
        uses: actions/upload-artifact@v3
        with:
          name: my-bumper.txt
          path: ./bumper.txt

      - name: List current directory
        run: ls

  download-artifacts:
    runs-on: ubuntu-latest
    needs: upload-artifacts
    steps:
      - uses: actions/checkout@v2

      - name: Download my bumper
        uses: actions/download-artifact@v3
        with:
          name: my-bumper.txt

      - name: List current directory
        run: ls
