name: pre-release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '16.15.0'

      - name: Debug
        uses: crazy-max/ghaction-dump-context@v1

      - name: Check if version has been updated
        id: version_check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub prerelease
        id: create_release
        # context property
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_check.outputs.version }}
          release_name: ${{ steps.version_check.outputs.version }}
          body: Thanks for following along! For more information check out the [CHANGELOG](https://github.com/bafu/hackga/blob/master/CHANGELOG.md).
          prerelease: true